### ISSUE TITLE
JOSS review: clarify in documentation what is the user-facing API

### ISSUE THREAD

**Issue by jpata** [umami-hep/umami#3]
Make it clear in the documentation what part of the library is supposed to be built on by the users, and what part is internal and may change.

**Comment by philippgadow** [comment]
Dear @jpata,
thank you for opening the issue. We agree and have added a section about intended use in the landing page of the documentation: https://umami.docs.cern.ch

Specifically, we write:

> The intended use is as a software using configuration files to carry out preprocessing, training and evaluation. It is not written with its use as a library in mind, as its core functionalities are provided by separate python modules which in turn can be installed with pip.

These are:

[ATLAS flavour tagging tools](https://github.com/umami-hep/atlas-ftag-tools)
[Umami preprocessing](https://github.com/umami-hep/umami-preprocessing)
[puma – Plotting UMami API](https://github.com/umami-hep/puma)

Do you think this is sufficiently clear?
