### ISSUE TITLE
[JOSS Review]: Suggested paper revisions

### ISSUE THREAD

**Issue by matthewfeickert** [umami-hep/umami#5]
These are some comments to help the paper component of https://github.com/openjournals/joss-reviews/issues/5833 be more compliant with a JOSS paper. @philippgadow's revisions have already improved things quite a bit, so great job there. :+1: 

* [ ] In the ["What should my paper contain?"](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) JOSS docs it notes that the paper should include

> A summary describing the high-level functionality and purpose of the software for a diverse, _non-specialist_ audience.

However, the first setnance of the paper

https://github.com/umami-hep/umami/blob/995170a9378a739be425248d08a9360775aa9699/paper/paper.md?plain=1#L111

mentions jets with no introduction. Non-speacialist here means people outside of particle physics, and so a description of what a jet is minimally required (though it can and should be extremeley brief). While you don't need to also go into great detail as to what the Standard Model there should be some (few word) mention.

* [ ] In 

https://github.com/umami-hep/umami/blob/995170a9378a739be425248d08a9360775aa9699/paper/paper.md?plain=1#L121

the 

```
It is deployed as a Python module which can be installed with `setuptools` [@setuptools:2023] or used via Docker images [@Merkel:2014].
```

part should be reviesed for accuracy to something like

```
It is available as a Python application and is also distributed via Linux container images.
```

as:
* `umami` currently isn't deployed anywhere as it isn't packaged properly (I'll open a follow up issue on that after this in a few hours) and available on an public Python package index like (the default) PyPI or an alternative.
* `umami` relies heavily on an [(incomplete) `requirements.txt`](https://github.com/umami-hep/umami/blob/e19017383d1385978d7926b036e284f7602fee30/requirements.txt) with exact version pins, making it seem that the intent is to have `umami` be a [Python application and not a library](https://iscinumpy.dev/post/app-vs-library/).
* The use of `setuptools` as a [build backend](https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend) (`setuptools` is not an installer) isn't something that needs to be brought up as a user should not ever need to care about how the developer's choice of build backend.
* Linux container images _are_ distributed as Docker images on Docker Hub under the `btagging/umami` image repository and as Singularity images on CVMFS

* [ ] The entire "Development Notes" section

https://github.com/umami-hep/umami/blob/995170a9378a739be425248d08a9360775aa9699/paper/paper.md?plain=1#L128-L132

should be removed as it isn't relevant for the paper.

* [ ] In 

https://github.com/umami-hep/umami/blob/995170a9378a739be425248d08a9360775aa9699/paper/paper.md?plain=1#L149

these are libraries, not modules.

* [ ] In https://github.com/openjournals/joss-reviews/issues/5833#issuecomment-1983038931 there are a number of DOIs missing, but flagged bibliographic items like

https://github.com/umami-hep/umami/blob/995170a9378a739be425248d08a9360775aa9699/paper/paper.bib#L25-L32

are also not cited anywhere in the paper and so can just be removed. Other like

https://github.com/umami-hep/umami/blob/995170a9378a739be425248d08a9360775aa9699/paper/paper.bib#L358-L370

that don't have a DOI (somewhat surprisingly) can be safely ignored.

So just a few things left on the paper, but looking very much improved! :+1:

**Comment by philippgadow** [comment]
Dear @matthewfeickert,

Thank you for taking the time for the thorough editorial review and comments.
Please find the answers here:

- request: add explanation of what a jet is
    - answer: we rephrased the first sentence (additions marked in italics) 

    "Flavour-tagging, the identification of *collimated sprays of particles ("jets")* originating from bottom and charm quarks, is a critically important technique in the data analysis of the ATLAS experiment [@ATLAS:2008] at the Large Hadron Collider [@Evans:2008]."

- request: change "It is deployed as a Python module which can be installed with `setuptools` [@setuptools:2023] or used via Docker images [@Merkel:2014]." to "It is available as a Python application and is also distributed via Linux container images."
    - answer: Done

- request: remove "Development notes" section
    - answer: Done

- request: change " The performance of the chosen model can be evaluated in publication-grade plots, which are steered with configuration files. The plots are created using the `matplotlib` [@Hunter:2007] and `puma` [@Birk:2023] Python modules." to " The performance of the chosen model can be evaluated in publication-grade plots, which are steered with configuration files. The plots are created using the `matplotlib` [@Hunter:2007] and `puma` [@Birk:2023] Python libraries."
    - answer: Done

- request: clean bibliography
    - answer: Done

Please close the comment and mark the checkboxes if you find our responses satisfactory. If not, we are happy to iterate here.

**Comment by matthewfeickert** [comment]
Thanks for the fast turn around @philippgadow! From this latest build (https://github.com/openjournals/joss-reviews/issues/5833#issuecomment-1985338649) I think this is looking very good.

One final revision is that in

https://github.com/umami-hep/umami/blob/314f991e499a50b5bf04de8849546cd2b39f193f/paper/paper.md?plain=1#L110

```
It is applied in precision measurements of the Standard Model, e.g. in characterisations of the Higgs boson properties, as well as in searches for yet unknown phenomena.
```

introduces the Standard Model, but non-physicsts won't know what that is. So if you put in a similar level explanation as you did for jets (e.g. less than a sentence) that would be great.

After that I think the paper is ready to go. :+1:

**Comment by philippgadow** [comment]
Hi @matthewfeickert !

I think that if readers don't know what the Standard Model is, then they also will not know what a Higgs boson or a bottom or charm quark are. However, I see the point of making the paper accessible to a non-specialist audience, so I rephrased as follows:

The sentence 

> It is applied in precision measurements of the Standard Model, e.g. in characterisations of the Higgs boson properties, as well as in searches for yet unknown phenomena.

has been rephrased to

> It is applied in precision measurements of the Standard Model of particle physics,
which is the theory describing fundamental forces and classifying all known elementary particles, as well as in searches for yet unknown phenomena.

I appreciate the level of detail you take in the review, thank you!

**Comment by matthewfeickert** [comment]
> [!NOTE] 
> Context on the delay between the last communications is here: https://github.com/openjournals/joss-reviews/issues/5833#issuecomment-2384778921

---

Okay. While the seciton

https://github.com/umami-hep/umami/blob/fe0f292d16d380c8c2817d87bb4046045f0591c6/paper/paper.md?plain=1#L127

isn't needed, I think it is okay to keep in so that this can move forward towards publication. I'll close this as done now.
